name: Kondukto Scan on PR and Push

on:
  push:
    branches:
      - pr-decoration-test3
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  kondukto-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh

      - name: Run KDT Scan
        env:
          KONDUKTO_TOKEN: ${{ secrets.KONDUKTO_TOKEN }}
        run: |
          kdt ping --host https://35.189.242.21 --token "$KONDUKTO_TOKEN" --insecure

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: |
          bandit -r . -f json -o bandit-report.json || true

      - name: Upload Bandit Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

      - name: Check Directory
        run: |
          ls /home/runner/work/
